name: Scan file and Push to Dependency-Track

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.85.0

      - name: Scan Docker image with Syft
        run: syft dir:. -o cyclonedx-json --file syft-output.json

      - name: Upload Syft output to Dependency-Track
        uses: actions/upload-artifact@v3
        with:
          name: syft-output
          path: syft-output.json

      # Assuming you have an API to push to Dependency-Track, adjust as necessary
      - name: Push results to Dependency-Track
        run: |
          curl -X POST http://34.142.201.115/api/v1/bom \
            -H "Content-Type: multipart/form-data" \
            -H "X-API-Key: ADHTh2hlZ74DNtCupCl4HnxuMZOYIT31" \
            -F "projectName=${{ github.repository }}-cmu" \
            -F "autoCreate=true" \
            -F "projectVersion=workshop" \
            -F "bom=@syft-output.json"